# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://lexlogic.github.io"  # Include trailing slash
# title = "Clarity"
copyright = "Copyright © 2022, Logic; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "clarity"
#disqusShortname = "lexlogic"

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.en.toml

[permalinks]
  post = '/:year/:month/:title'


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
