backend:
  name: git-gateway
  repo: lexlogic/lexlogic.github.io
  branch: main # Branch to update (optional; defaults to master)
media_folder: "images"
public_folder: "images"
publish_mode: editorial_workflow
logo_url: https://logicsec.io/logos/logo-dark.png
collections:

  - name: settings
    label: Settings
    label_singular: 'Settings'
    files:
      - label: Authors
        name: authors
        file: data/authors.json
        fields:
          - label: Authors
            name: authors
            widget: list
            allow_add: true
            fields:
              - label: Name
                name: name
                widget: string
              - label: About
                name: about
                widget: string
              - label: Email
                name: email
                widget: string

  - name: 'post'
    label: 'Post'
    folder: 'content/post'
    path: '{{year}}/{{month}}/{{slug}}/index'
    preview_path: post/{{slug}}
    nested:
      depth: 100
      summary: '{{title}}'
    create: true
    editor:
      preview: false
    show_preview_links: true
    fields:
      - label: Draft
        name: draft
        widget: boolean
        default: true
        required: false

      - label: Author
        name: author
        widget: relation
        collection: settings
        value_field: authors.*.name
        search_fields: [authors.*.name]
        display_fields: [authors.*.name]
        file: authors
        multiple: true

      - label: Title
        name: title
        widget: string

      - label: Date
        name: date
        widget: datetime

      - label: Description
        name: description
        widget: string
        required: false

      - label: Featured
        name: featured
        widget: boolean
        required: false

      - label: Show Table of Contents
        name: toc
        widget: boolean
        required: false

      - label: Use Page Bundles
        name: usePageBundles
        widget: boolean
        default: true
        required: false

      - label: Featured Image
        name: featureImage
        widget: image
        media_folder: images
        default: /images/thumbnail.jpg

      - label: Featured Image Caption
        name: featureImageCap
        widget: string
        required: false

      - label: Thumbnail
        name: thumbnail
        widget: image
        media_folder: images
        default: /images/thumbnail.jpg

      - label: Social Image
        name: shareImage
        widget: image
        media_folder: images
        default: /images/thumbnail.jpg

      - label: Show Code Lines
        name: codeLineNumbers
        widget: boolean
        default: true
        required: false

      - label: Number of Code Lines
        name: codeMaxLines
        widget: number
        default: 10

      - label: Show Figure Label
        name: figurePositionShow
        widget: boolean
        default: true
        required: false

      - label: Show Related Articles
        name: showRelatedInArticle
        widget: boolean
        default: true
        required: false

      - label: Body
        name: body
        widget: markdown
        media_folder: "images"
        public_folder: "images"

      - label: "Categories"
        name: "categories"
        widget: "list"
        summary: '{{fields.name}}'
        field: {label: Name, name: name, widget: string}

      - label: "Tags"
        name: "tags"
        widget: "list"
        summary: '{{fields.name}}'
        field: {label: Name, name: name, widget: string}