[[main]]
  name = "Home"
  url = ""
  weight = -110

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Categories"
  identifier = "Series"
  weight = -108
[[main]]
  parent = "Series"
  name = "Security"
  url = "categories/security/"
[[main]]
  parent = "Series"
  name = "Write-Up"
  url = "categories/security/"
[[main]]
  parent = "Series"
  name = "Microsoft"
  url = "categories/security/"
[[main]]
  parent = "Series"
  name = "Technology"
  url = "categories/security/"

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/lexlogic"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/nicholiknight/"
[[social]]
name = "twitter"
weight = 4
url = "https://twitter.com/logicsecnews"
[[social]]
name = "rss"
weight = 5
url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"